version: 2

sources:
  - name: staging
    database: dtc-de-course-462612
    schema: homework4_dataset

    tables:
      - name: external_green_nytaxi
      - name: external_yellow_nytaxi
